#!#!/bin/bash

cd ~/

rm -r ram && touch ram

echo $(zenity --entry --title "RAM Allocation" --text "Enter The Amount Of Ram in Megabytes. Default is 2000") >> ram
pkexec mv ~/ram /usr/share/auradroid/config
